# Generated by Django 4.2.1 on 2023-05-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observable',
            old_name='activity',
            new_name='connect_time',
        ),
    ]
